files:
  - source: src/main/resources/lang/installer.properties
    translation: /src/main/resources/lang/installer_%locale_with_underscore%.properties
    escape_quotes: 0
    escape_special_characters: 0